export const MOTIVATIONAL_PHRASES = [
  "El único modo de hacer un gran trabajo es amar lo que haces.",
  "La innovación distingue a los líderes de los seguidores.",
  "Tu tiempo es limitado, no lo desperdicies viviendo la vida de otro.",
  "La vida es un 10% lo que te ocurre y un 90% cómo reaccionas.",
  "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
  "El conocimiento es poder.",
  "No cuentes los días, haz que los días cuenten.",
  "El aprendizaje nunca agota la mente.",
  "Siempre parece imposible hasta que se hace.",
  "La educación es el arma más poderosa que puedes usar para cambiar el mundo.",
  "El futuro pertenece a aquellos que creen en la belleza de sus sueños.",
  "La inteligencia es la habilidad de adaptarse al cambio.",
  "Lo único imposible es aquello que no intentas.",
  "Cree en ti mismo y en todo lo que eres.",
  "El único límite a nuestra realización de mañana serán nuestras dudas de hoy.",
  "La creatividad es la inteligencia divirtiéndose.",
  "Haz de cada día tu obra maestra.",
  "El secreto para salir adelante es empezar.",
  "La mejor manera de predecir el futuro es creándolo.",
  "No busques los errores, busca un remedio.",
  "La perseverancia es el trabajo duro que haces después de cansarte.",
  "Un viaje de mil millas comienza con un solo paso.",
  "Las grandes cosas nunca vinieron de zonas de confort.",
  "Trabaja duro en silencio, que tu éxito sea tu ruido.",
  "Apunta a la luna. Si fallas, podrías dar a una estrella.",
  "Todo lo que siempre has querido está al otro lado del miedo.",
  "La disciplina es el puente entre metas y logros.",
  "Haz lo que puedas, con lo que tengas, donde estés.",
  "Nunca es demasiado tarde para ser lo que podrías haber sido.",
  "La acción es la clave fundamental de todo éxito.",
  "Nuestra mayor gloria no es no caer nunca, sino levantarnos cada vez.",
  "No te limites. Puedes ir tan lejos como tu mente te permita.",
  "La confianza en uno mismo es el primer secreto del éxito.",
  "Si puedes soñarlo, puedes hacerlo.",
  "La voluntad encuentra el camino.",
  "La excelencia no es un acto, es un hábito.",
  "Lo que haces hoy puede mejorar todas tus mañanas.",
  "El fracaso es la oportunidad de comenzar de nuevo con más inteligencia.",
  "La verdadera motivación viene del logro, el desarrollo y la satisfacción.",
  "Tus talentos y habilidades mejorarán con el tiempo, pero para eso has de empezar.",
  "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.",
  "Somos lo que hacemos repetidamente.",
  "A veces, la magia es simplemente alguien que pasa más tiempo en algo que los demás.",
  "La motivación nos impulsa a comenzar y el hábito nos permite continuar.",
  "Pregúntate si lo que estás haciendo hoy te acerca al lugar en el que quieres estar mañana.",
  "La actitud es una pequeña cosa que marca una gran diferencia.",
  "No dejes que el ayer ocupe demasiado del hoy.",
  "La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra.",
  "Incluso la noche más oscura terminará y saldrá el sol.",
  "Si quieres cambiar el mundo, cámbiate a ti mismo.",
  "Cuanto más trabajo, más suerte parezco tener.",
  "No mires el reloj; haz lo que él hace. Sigue adelante.",
  "Las oportunidades no ocurren, las creas.",
  "Si la oportunidad no llama, construye una puerta.",
  "Los ganadores nunca se rinden y los que se rinden nunca ganan.",
  "Si caíste ayer, levántate hoy.",
  "Tu actitud, no tu aptitud, determinará tu altitud.",
  "Lo que no te mata, te hace más fuerte.",
  "Un sueño no se hace realidad a través de la magia; requiere sudor, determinación y trabajo duro.",
  "El pesimista ve dificultad en toda oportunidad. El optimista ve oportunidad en toda dificultad.",
  "No te detengas hasta que te sientas orgulloso.",
  "La vida se encoge o se expande en proporción a tu coraje.",
  "Solo yo puedo cambiar mi vida. Nadie puede hacerlo por mí.",
  "No puedes cruzar el mar simplemente mirando el agua.",
  "Cree que puedes y ya estarás a medio camino.",
  "Cada momento es un nuevo comienzo.",
  "Inténtalo de nuevo. Fracasa de nuevo. Fracasa mejor.",
  "Hazlo ahora. A veces 'después' se convierte en 'nunca'.",
  "Cuanto mayor sea la dificultad, mayor será la gloria.",
  "Para tener éxito, primero debemos creer que podemos.",
  "La vida es una aventura atrevida o nada en absoluto.",
  "El éxito consiste en ir de fracaso en fracaso sin perder el entusiasmo.",
  "Los sueños son las ilustraciones del libro que tu alma está escribiendo.",
  "Eres capaz de mucho más de lo que estás pensando, imaginando o haciendo ahora.",
  "La paciencia es amarga, pero su fruto es dulce.",
  "El único obstáculo entre ti y tu objetivo es la historia que te cuentas a ti mismo.",
  "En medio de la dificultad reside la oportunidad.",
  "La acción vence al miedo.",
  "Visualiza tus metas y persíguelas sin descanso.",
  "Atrévete a ser grande.",
  "Toda gran victoria empieza con una pequeña batalla interna.",
  "Eres el arquitecto de tu propio destino.",
  "La sabiduría comienza con la curiosidad.",
  "Transforma tus dudas en combustible para tu éxito.",
  "Concéntrate en la solución, no en el problema.",
  "Lo que construyes hoy será tu fortaleza mañana.",
  "Respira profundo y sigue adelante.",
  "La resiliencia es el secreto de los campeones.",
  "Las mentes grandes discuten ideas.",
  "Supera tus límites todos los días.",
  "Nunca te disculpes por tener altos estándares.",
  "Mantén la vista en las estrellas y los pies en la tierra.",
  "Eres una obra maestra en progreso.",
  "Todo es posible con la actitud correcta.",
  "La determinación es el despertador de tu voluntad.",
  "Acepta el reto para sentir la euforia de la victoria.",
  "El universo premia la valentía.",
  "Tu mejor maestro es tu último error.",
  "Despierta con determinación y acuéstate con satisfacción.",
  "La constancia siempre supera al talento."
];
